### ISSUE TITLE
Example does not seem to run

### ISSUE THREAD

**Issue by Notice-Jeroen-Meijer** [LanguageMachines/lexiconenrichment#1] opened 2020-08-24 17:45 UTC
I did a clean docker build, created an inputfile with just the content
```
binnnenkomststempel,10
```
Here is the result
```
lamachine@182f55f6cf7d:~/lexiconenrichment$ ./clean_run.sh inputfile.txt outputfile.txt
inputfile inputfile.txt
 ticcl.nf --inputdir inputdata --inputtype text --lexicon /usr/local/opt/PICCL/data/int/nld/nld.aspell.dict --alphabet /usr/local/opt/PICCL/data/int/nld/nld.aspell.dict.lc.chars --charconfus /usr/local/opt/PICCL/data/int/nld/nld.aspell.dict.c20.d2.confusion --outputdir inputdata/ticcle-output --nofoliacorrect 
N E X T F L O W  ~  version 20.07.1
Launching `/usr/local/bin/ticcl.nf` [scruffy_wright] - revision: 83ea311240
--------------------------
TICCL Pipeline
--------------------------
TICCL text input: inputfile.txt.clean
executor >  local (3)
[2c/fd2743] process > txt2folia (1)       [100%] 1 of 1 ✔
[8e/71956f] process > corpusfrequency (1) [100%] 1 of 1 ✔
[93/c9539c] process > ticclunk (1)        [  0%] 0 of 1
[-        ] process > anahash             -
[-        ] process > indexer             -
[-        ] process > resolver            -
[-        ] process > rank                -
[-        ] process > chainer             -
Error executing process > 'ticclunk (1)'

Caused by:
  Process `ticclunk (1)` terminated with an error exit status (1)

Command executed:

  #!/bin/bash
  set +u
  if [ ! -z "" ]; then
      source /bin/activate
  fi
  set -u
  
  TICCL-unk --background "nld.aspell.dict" --artifrq 10000000 --alph "nld.aspell.dict.lc.chars" "corpus.wordfreqlist.tsv" || exit 1
executor >  local (3)
[2c/fd2743] process > txt2folia (1)       [100%] 1 of 1 ✔
[8e/71956f] process > corpusfrequency (1) [100%] 1 of 1 ✔
[93/c9539c] process > ticclunk (1)        [100%] 1 of 1, failed: 1 ✘
[-        ] process > anahash             -
[-        ] process > indexer             -
[-        ] process > resolver            -
[-        ] process > rank                -
[-        ] process > chainer             -
Error executing process > 'ticclunk (1)'

Caused by:
  Process `ticclunk (1)` terminated with an error exit status (1)

Command executed:

  #!/bin/bash
  set +u
  if [ ! -z "" ]; then
      source /bin/activate
  fi
  set -u
  
  TICCL-unk --background "nld.aspell.dict" --artifrq 10000000 --alph "nld.aspell.dict.lc.chars" "corpus.wordfreqlist.tsv" || exit 1
  
  if [ ! -s "corpus.wordfreqlist.tsv.clean" ]; then
      echo "ERROR: Expected output corpus.wordfreqlist.tsv.clean does not exist or is empty">&2
      exit 6
  fi

Command exit status:
  1

Command output:
  (empty)

Command error:
  TICCL-unk: error while loading shared libraries: libticcl.so.1: cannot open shared object file: No such file or directory

Work dir:
  /home/lamachine/lexiconenrichment/work/93/c9539c9369c06c54cfb3265cb029a8

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

lamachine@182f55f6cf7d:~/lexiconenrichment$ ls
clean_run.sh		     Dockerfile		
```
The clean file was creates, as was the inputdata folder, but (of course) no result.

**Comment by proycon** [comment] 2020-08-24 20:34
I came across that same issue during development too, but I thought I had fixed it and it hadn't resurfaced in my latest test. But indeed, I can reproduce it too. I just committed a small fix. Can you delete your old docker container & image and build one again with the new dockerfile?

**Comment by Notice-Jeroen-Meijer** [comment] 2020-08-24 21:11
Thanks

I now get an error in the indexer, error 6
```
ERROR: Expected output corpus.wordfreqlist.tsv.clean.indexNT does not exist or is empty
```
While just before it indicated it wrote that. Will try again tomorrow

**Comment by proycon** [comment] 2020-08-24 22:13
It seems something went wrong in the underlying system indeed (ticcl). I'm not really familiar with the internals, but the output file is unexpectedly empty after that stage in the processing. I could reproduce it with your example:

```
Command executed:

  #!/bin/bash
  set +u
  if [ ! -z "" ]; then
      source /bin/activate
  fi
  set -u

  TICCL-indexerNT --hash "corpus.wordfreqlist.tsv.clean.anahash" --charconf "nld.aspell.dict.c20.d2.confusion" --foci "corpus.wordfreqlist.tsv.clean.corpusfoci" -o "corpu
s.wordfreqlist.tsv.clean" -t 1 --low 5 --high 35 || exit 1

  if [ ! -s "corpus.wordfreqlist.tsv.clean.indexNT" ]; then
      echo "ERROR: Expected output corpus.wordfreqlist.tsv.clean.indexNT does not exist or is empty">&2
      exit 6
  fi

Command exit status:
  6

Command output:
  reading corpus word anagram hash values
  read 206670 corpus word anagram values
  skipped 2424 out-of-band corpus word values
  read 1 foci values
  read 275652 character confusion anagram values
  created 1 separate experiments
  running on 1 threads.

  wrote indexes into: corpus.wordfreqlist.tsv.clean.indexNT

Command error:
  ERROR: Expected output corpus.wordfreqlist.tsv.clean.indexNT does not exist or is empty

Work dir:
  /home/lamachine/lexiconenrichment/work/8a/dbb342c43f9fc64ad16980ccf3e27b
```

@Irishx do you have a clue or do we need to ask @martinreynaert for clarification? It's not a pipeline problem (all input files are okay afaik).

**Comment by Irishx** [comment] 2020-08-25 10:52
Okay we took a long time to find the reason for this behaviour and we can consider this a 'feature not a bug' ;-)

So Iris gave a fabricated example instead of a real example in the README file, this has been adapted now.
The spelling checker is intented to work on corpora, big amounts of text input. in this case the example cons

**Comment by Irishx** [comment] 2020-08-25 10:53
Okay we took a long time to find the reason for this behaviour and we can consider this a 'feature not a bug' ;-)

So Iris gave a fabricated example instead of a real example in the README file, this has been adapted now.
The spelling checker is intented to work on corpora, big amounts of text input. In this case the example consisted of a compound 'binnnenkomststempel' and the spelling-checker did not find any alternative candidates for this word as the correct form dus not exist in the background lexicon (and the spelling-checker does not de-compound words).
As there were not corrections made, this was leading to an empty file, which leads to an error.
We made an issue in the spelling-checker that we should handle this with a mor informative error message.

The software does not work on single word inputs, but only on longer word lists.

**Closed as completed** 2020-08-25 10:57 UTC
Labels: bug

**Comment by Notice-Jeroen-Meijer** [comment] 2020-08-25 11:11
I do not quite understand the above described behavior, but will do a few tests to get things clearer in my mind. Furthermore:
1) what is the minimum word list size then?
2) do I understand correctly that if a word is misspelled, but the spell checker can not find an alternative, the word is dropped from the output entirely? If so we need to detect these cases and steer towards manual correction.
3) I would mostly appreciate a working input file example in the repository or otherwise as to separate runtime issues from logical errors. This greatly simplifies integration work.
